from pathlib import Path
import json
p=Path(__file__).parent/'source/website-content.txt'
# The owner's MBT correction overrides the original document's acronym only.
source={int(line[:4]):line[5:].replace('BMT','MBT') for line in p.read_text().splitlines()}
def rows(a,b):return [source[n] for n in range(a,b+1)]
en={'about':rows(9,13),'vision':source[22].split(': ',1)[1],'mission':source[23].split(': ',1)[1],'localization':rows(25,31),'representation':rows(33,41),'industrial':rows(43,49),'why':rows(59,66),'sectors':rows(69,76),'support':rows(78,85),'governance':rows(91,96),'intro':source[6]}
en['titles']=['Homepage / Introduction','About MBT','Vision & Mission','Saudi Vision 2030 & Localization','International Representation & Market Access','Industrial & Manufacturing Development','Leadership Team','Why Partner With MBT','Strategic Areas of Interest','After-Contract Award Support','International Partnerships','Governance & Compliance','Contact / Partner With MBT']
en['partnership']='Focus on long-term representation and cooperation rather than only individual transactions.'
en['industrialNote']='Planned industrial development and localization.'
en['visionLabel']='Vision';en['missionLabel']='Mission';en['foundationNote']='MBT is a newly established defense company, but it is backed by an established group and managed by experienced people.'
ar={
 'titles':['الرئيسية / التعريف','عن MBT','الرؤية والرسالة','رؤية السعودية 2030 والتوطين','التمثيل الدولي ودخول السوق','التطوير الصناعي والتصنيع','فريق القيادة','لماذا الشراكة مع MBT','مجالات الاهتمام الاستراتيجية','الدعم بعد ترسية العقود','الشراكات الدولية','الحوكمة والامتثال','تواصل معنا / الشراكة مع MBT'],
 'intro':'MBT شركة سعودية في قطاع الدفاع والأمن، تأسست لربط المصنّعين الدفاعيين الدوليين الرائدين بالفرص في المملكة العربية السعودية. تستند الشركة إلى دعم مجموعة سعودية قابضة قائمة، ويقودها فريق إداري ذو خبرة، وتقدم خدمات التمثيل في السوق وتطوير الأعمال ودعم التوطين والخدمات داخل المملكة للشركاء الدوليين الساعين إلى نمو مستدام في السوق السعودي.',
 'about':['شركة سعودية في قطاع الدفاع والأمن.','جزء من مجموعة سعودية قابضة قائمة تعمل بنجاح في المملكة منذ سنوات عديدة.','مدعومة بالبنية المؤسسية للمجموعة القابضة وخبرتها في الأعمال المحلية.','يديرها كوادر مؤهلة بخبرات دفاعية وتجارية وتشغيلية ومالية.','تركز على بناء علاقات طويلة المدى مع مصنّعين دفاعيين دوليين ذوي سمعة موثوقة.'],
 'vision':'أن نصبح شريكًا سعوديًا موثوقًا للشركات الدولية الرائدة في قطاعي الدفاع والأمن.',
 'mission':'ربط القدرات الدولية بالاحتياجات السعودية، مع دعم التوطين ونقل التقنية والتنمية الصناعية المستدامة.',
 'visionLabel':'الرؤية','missionLabel':'الرسالة',
 'localization':['التوافق مع رؤية السعودية 2030 ومستهدفات المملكة لتوطين قطاع الدفاع.','دعم الشركاء الدوليين في تطوير خطط عملية للتوطين في السعودية.','نقل التقنية والمعرفة.','فرص التجميع والتصنيع المحلي.','تطوير القدرات الفنية والكوادر السعودية.','تطوير سلاسل الإمداد المحلية.','دعم الشركاء الدوليين في فهم سوق الدفاع السعودي والبيئة التنظيمية ومتطلبات التوطين.'],
 'representation':['تمثيل مصنّعين دفاعيين دوليين مختارين في السعودية.','دعم دخول السوق السعودي وتطوير الأعمال.','تحديد الفرص ذات الصلة ومتابعتها.','المعلومات السوقية ودعم السوق المحلي.','التواصل مع الجهات المعنية.','تنسيق الاجتماعات والعروض التعريفية واستعراض المنتجات.','دعم فرص المناقصات والمشتريات.','تنسيق العروض والجوانب التجارية.','الدعم داخل المملكة.'],
 'industrial':['تطوير التصنيع المحلي.','التجميع والتكامل.','نقل التقنية.','فرص التصنيع المشترك.','مشاريع مشتركة محتملة مع المصنّعين الأصليين الدوليين.','تطوير سلاسل الإمداد السعودية.','تطوير القدرات الإنتاجية المستقبلية وفق احتياجات السوق السعودي.'],
 'industrialNote':'التطوير الصناعي والتوطين المخطط لهما.',
 'why':['قيادة ذات خبرة.','معرفة قوية بالسوق السعودي.','دعم مجموعة قابضة قائمة.','الاستفادة من بنية الأعمال المحلية.','نهج للشراكات الدولية.','التركيز على رؤية 2030 والتوطين.','تمثيل محلي طويل المدى.','دعم تجاري وتشغيلي.'],
 'foundationNote':'MBT شركة دفاعية حديثة التأسيس، تستند إلى دعم مجموعة قائمة ويديرها أشخاص ذوو خبرة.',
 'sectors':['الأنظمة البرية','أنظمة الطيران والفضاء','الأنظمة البحرية','أنظمة C4ISR','الحرب الإلكترونية','أنظمة مكافحة الطائرات غير المأهولة','الذخائر','أنظمة الأسلحة'],
 'support':['تنسيق تنفيذ العقود.','التنسيق داخل المملكة مع الشركاء الدوليين.','دعم التواصل مع الجهات الحكومية والعملاء.','تنسيق التسليم والخدمات اللوجستية.','تنسيق الوثائق والجوانب التنظيمية.','التنسيق مع الشركاء المحليين والجهات المعنية.','المتابعة طوال تنفيذ العقد.','دعم التزامات التوطين عند انطباقها.'],
 'partnership':'التركيز على التمثيل والتعاون طويل المدى، بما يتجاوز الصفقات الفردية.',
 'governance':['أخلاقيات الأعمال.','الالتزام بالأنظمة واللوائح السعودية ذات الصلة.','مبادئ مكافحة الرشوة والفساد.','الوعي بضوابط التصدير.','السرية وحماية المعلومات.','ممارسات الأعمال الدولية المسؤولة.']}
# Owner-approved revisions to sections 3, 8 and 12, September 2026.
en.update({
 'vision':'To be a leading Saudi company in the defense and security sector, advancing national capabilities and building trusted international partnerships.',
 'mission':'To contribute to the advancement of the Saudi defense and security sector by supporting our partners, connecting international expertise with national needs, and enabling localization, technology transfer, and sustainable industrial development.',
 'why':['Experienced leadership.','In-depth knowledge of the Saudi market.','Support from an established holding group.','Access to local business infrastructure.','A strategic approach to international partnerships.','A focus on Saudi Vision 2030 and localization.','Long-term representation in Saudi Arabia.','Commercial and operational expertise.','High commitment to our partners’ success.','Dedicated partner support, from market entry through contract execution.'],
 'foundationNote':'MBT is a well-established defense company backed by an established group and led by experienced professionals.',
 'governance':['Ethical business practices.','Compliance with applicable Saudi laws and regulations.','Awareness of export control requirements.','Confidentiality and protection of information.','Responsible international business practices.']
})
ar.update({
 'vision':'أن نكون شركة سعودية رائدة في قطاع الدفاع والأمن، تسهم في تطوير القدرات الوطنية وبناء شراكات دولية موثوقة.',
 'mission':'الإسهام في تطوير قطاع الدفاع والأمن السعودي من خلال دعم شركائنا، وربط الخبرات الدولية بالاحتياجات الوطنية، وتمكين التوطين ونقل التقنية والتنمية الصناعية المستدامة.',
 'why':['قيادة ذات خبرة.','معرفة عميقة بالسوق السعودي.','دعم من مجموعة قابضة راسخة.','الاستفادة من البنية التحتية للأعمال المحلية.','نهج استراتيجي لبناء الشراكات الدولية.','التركيز على رؤية السعودية 2030 والتوطين.','تمثيل طويل الأمد في المملكة.','خبرات تجارية وتشغيلية.','التزام عالٍ بنجاح شركائنا.','دعم متواصل لشركائنا، من دخول السوق إلى تنفيذ العقود.'],
 'foundationNote':'MBT شركة راسخة في قطاع الدفاع، تستند إلى دعم مجموعة قائمة ويقودها فريق من ذوي الخبرة.',
 'governance':['ممارسات أعمال أخلاقية.','الامتثال للأنظمة واللوائح السعودية المعمول بها.','الإلمام بمتطلبات الرقابة على الصادرات.','الحفاظ على السرية وحماية المعلومات.','ممارسات مسؤولة في الأعمال الدولية.']
})
en['intro'] = en['intro'].replace('MBT', 'MBT (Modern Business Technologies)', 1)
ar['intro'] = ar['intro'].replace('MBT', 'MBT (Modern Business Technologies)', 1)

# Approved editorial review; preserve section order and factual scope.
en.update({'intro': 'MBT (Modern Business Technologies) is a Saudi defense and security company backed by an established holding group and an experienced leadership team. We support international manufacturers with Saudi market entry, business development, localization, and in-country services.', 'why': ['Defense-sector experience: leadership with more than 27 years at the Saudi Ministry of Defense.', 'International partnerships: experience working with U.S. and European defense manufacturers.', 'Operational and financial expertise: a team with backgrounds in project delivery, planning, and risk management.', 'Local business infrastructure: support from an established Saudi holding group.', 'Localization focus: helping partners develop practical plans aligned with Saudi Vision 2030.', 'Commitment to our partners: sustained support from market entry through contract execution.'], 'governance': ['Integrity and business ethics.', 'Compliance with applicable Saudi laws and regulations.', 'Awareness of export control requirements.', 'Confidentiality and protection of information.', 'Responsibility in international business dealings.']})
ar.update({'intro': 'MBT (Modern Business Technologies) شركة سعودية في قطاع الدفاع والأمن، تستند إلى دعم مجموعة قابضة ذات خبرة ويقودها فريق متمرس. ندعم المصنّعين الدوليين في دخول السوق السعودي وتطوير الأعمال والتوطين، ونقدم لهم خدمات الدعم داخل المملكة.', 'about': ['شركة سعودية متخصصة في قطاع الدفاع والأمن.', 'جزء من مجموعة سعودية قابضة تتمتع بخبرة ممتدة في المملكة.', 'تستفيد من البنية المؤسسية للمجموعة وخبرتها في السوق المحلي.', 'يقودها فريق يجمع خبرات في الدفاع والأعمال والعمليات والإدارة المالية.', 'تبني علاقات طويلة الأمد مع مصنّعين دوليين موثوقين في قطاع الدفاع.'], 'localization': ['دعم مستهدفات رؤية السعودية 2030 لتوطين قطاع الدفاع.', 'مساعدة الشركاء الدوليين على وضع خطط عملية للتوطين في المملكة.', 'دعم نقل التقنية والمعرفة.', 'تحديد فرص التجميع والتصنيع المحلي.', 'تطوير القدرات الفنية وتأهيل الكوادر السعودية.', 'تطوير سلاسل الإمداد المحلية.', 'مساعدة الشركاء على فهم السوق السعودي والأنظمة ومتطلبات التوطين.'], 'representation': ['تمثيل نخبة من المصنّعين الدوليين في قطاع الدفاع داخل المملكة.', 'دعم دخول السوق السعودي وتطوير الأعمال.', 'تحديد الفرص المناسبة ومتابعتها.', 'تحليل السوق وتوفير المعلومات لدعم قرارات الشركاء.', 'التواصل مع الجهات المعنية.', 'تنسيق الاجتماعات والعروض التعريفية والتجارب التوضيحية للمنتجات.', 'دعم المشاركة في المناقصات وفرص التوريد.', 'تنسيق إعداد العروض والجوانب التجارية.', 'تقديم الدعم المحلي للشركاء داخل المملكة.'], 'industrial': ['تطوير فرص التصنيع المحلي.', 'التجميع وتكامل الأنظمة.', 'نقل التقنية.', 'استكشاف فرص التصنيع المشترك.', 'بحث فرص إقامة مشاريع مشتركة مع المصنّعين الدوليين للمعدات الأصلية.', 'تطوير سلاسل الإمداد السعودية.', 'بناء قدرات إنتاجية مستقبلية تلبي احتياجات السوق السعودي.'], 'industrialNote': 'مجالات نستهدف تطويرها ضمن خطط التصنيع والتوطين.', 'why': ['خبرة في القطاع الدفاعي: قيادة تتمتع بخبرة تزيد على 27 عامًا في وزارة الدفاع السعودية.', 'شراكات دولية: خبرة في العمل مع مصنّعين دفاعيين أمريكيين وأوروبيين.', 'خبرات تشغيلية ومالية: فريق يجمع خبرات في تنفيذ المشاريع والتخطيط وإدارة المخاطر.', 'بنية مؤسسية محلية: دعم من مجموعة سعودية قابضة ذات خبرة.', 'تركيز على التوطين: مساعدة الشركاء على وضع خطط عملية تتوافق مع رؤية السعودية 2030.', 'التزام راسخ بنجاح شركائنا: دعم متواصل من دخول السوق إلى تنفيذ العقود.'], 'foundationNote': 'MBT شركة راسخة في قطاع الدفاع، تدعمها مجموعة ذات خبرة ويقودها فريق متمرس.', 'support': ['تنسيق أعمال تنفيذ العقود.', 'التنسيق مع الشركاء الدوليين داخل المملكة.', 'دعم التواصل مع الجهات الحكومية والعملاء.', 'تنسيق عمليات التسليم والخدمات اللوجستية.', 'متابعة المستندات والمتطلبات التنظيمية.', 'التنسيق مع الشركاء المحليين والجهات المعنية.', 'متابعة مراحل التنفيذ حتى إتمام العقد.', 'دعم الوفاء بالتزامات التوطين ذات الصلة بالعقد.'], 'partnership': 'نبني شراكات طويلة الأمد مع المصنّعين الدوليين، تقوم على التمثيل المحلي والتعاون المستمر في السوق السعودي.', 'governance': ['النزاهة وأخلاقيات العمل.', 'الامتثال للأنظمة واللوائح السعودية المعمول بها.', 'الإلمام بمتطلبات الرقابة على الصادرات.', 'الحفاظ على السرية وحماية المعلومات.', 'المسؤولية في التعاملات الدولية.']})
ar['titles'][4]='التمثيل الدولي ودخول السوق السعودي'
ar['titles'][6]='الفريق القيادي'
ar['titles'][7]='لماذا MBT؟'
ar['titles'][12]='تواصل معنا'
en['titles'][7]='Why MBT'
en['titles'][12]='Contact Us'
(Path(__file__).parent/'dist/source-content.js').write_text('window.MBT_SOURCE = '+json.dumps({'en':en,'ar':ar},ensure_ascii=False,indent=2)+';\n')
